version: '3.3'

services:
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - wp-content:/var/www/html
    networks:
      - yassir


  mariadb:
    image: mariadb
    container_name: Mariadb
    build: ./mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: websitedb
      MYSQL_USER: bloto
      MYSQL_PASSWORD: secret2001@
    ports:
      - 3306:3306
    networks:
      - yassir

  nginx:
    image: nginx
    container_name: nginx
    build: ./nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: unless-stopped
    volumes:
      - wp-content:/var/www/html/
    networks:
      - yassir
  
  adminer:
    image: adminer:bloto
    container_name: adminer
    build: ./adminer
    depends_on:
      - mariadb
    ports:
      - 8080:8080
    networks:
      - yassir
      
  staticpage:
    image: staticpage
    container_name: staticpage
    build: ./staticpage
    ports:
      - 100:100
    networks:
      - yassir
  ftp:
    image: ftp
    container_name: ftp
    build: ./ftp
    restart: always
    ports:
      - "21:21"
      - "20:20"
    volumes:
      -  wp-content:/home/test/ftp
    networks:
      - yassir

volumes:
  wp-content:
    driver_opts:
      o: bind
      type: none
      device: /Users/yel-aziz/desktop/database/wordpress
  


  # db-volume:
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: /Users/yel-aziz/desktop/database

networks:
  yassir:
    driver : bridge